### ISSUE TITLE
ImportError: No module named 'mongoengine'

### ISSUE THREAD

**Issue by fadc80** [sahildua2305/hackIDE#42]
I'm a python newbie trying to run this project with python3...

**$ python3 manage.py collectstatic**

The following error is being reported:

```
Traceback (most recent call last):
  File "/home/root/git/hackIDE/hackIDE-virtualenv/lib/python3.5/site-packages/django/conf/__init__.py", line 132, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/root/git/hackIDE/hackIDE-virtualenv/lib/python3.5/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/root/git/hackIDE/hackIDE_project/settings.py", line 14, in <module>
    from mongoengine import connect
ImportError: No module named 'mongoengine'
```

What am I doing wrong?

I have installed these packages:

**$ pip freeze**

```
Django==1.5.11
django-mongodb-engine==0.6.0
djangotoolbox==1.8.0
pymongo==3.3.0
```

I couldn'it figure it out.

Thank you.

**Comment by fadc80** [comment]
I've found it! Before running the server try...

`pip install -p requirements.txt`

**Comment by hesamnobari** [comment]
I have trouble with requirements module models!
I've installed mongoengine

**Comment by sahildua2305** [comment]
@hesamnobari what trouble exactly?

**Comment by hesamnobari** [comment]
ImportError: No module named 'models' ( for running server )


NameError: name 'long' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b5qxso6e/models/

( when use  pip install models)

**Comment by hesamnobari** [comment]
pip install models
Collecting models
  Using cached models-0.9.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-b5qxso6e/models/setup.py", line 25, in <module>
        import models
      File "/tmp/pip-build-b5qxso6e/models/models/__init__.py", line 24, in <module>
        from props import *
      File "/usr/local/lib/python3.5/dist-packages/props/__init__.py", line 92, in <module>
        long: lambda: long(arbitrary(int)) * arbitrary(int),
    NameError: name 'long' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b5qxso6e/models/

(complete error for pip install models)
